"""
AYO AI — Document Creator
==========================
Creates professional PDFs and PowerPoint presentations from voice/text prompts.
Also generates HTML/CSS/JS vibe-code snippets.
"""

import logging
import json
from pathlib import Path
from datetime import datetime

# PDF
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                  Table, TableStyle, HRFlowable)
from reportlab.lib.enums import TA_CENTER, TA_LEFT

# PowerPoint
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

log = logging.getLogger("ayo.docs")

DOCS_DIR = Path(__file__).parents[2] / "data" / "documents"
DOCS_DIR.mkdir(parents=True, exist_ok=True)

# ── Brand Colors ──────────────────────────────────────────────────────────────
PRIMARY   = colors.HexColor("#7C3AED")   # Ayo purple
SECONDARY = colors.HexColor("#06B6D4")   # Cyan accent
DARK      = colors.HexColor("#0F172A")   # Near-black
LIGHT     = colors.HexColor("#F8FAFC")   # Off-white


class DocumentCreator:

    # ══════════════════════════════════════════════════════════════════════════
    # PDF
    # ══════════════════════════════════════════════════════════════════════════

    def create_pdf(self, topic: str, content: str, filename: str = None) -> str:
        """Create a styled PDF document. Returns the saved file path."""
        if not filename:
            safe = "".join(c if c.isalnum() else "_" for c in topic)[:30]
            filename = f"{safe}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        path = str(DOCS_DIR / filename)

        doc = SimpleDocTemplate(
            path, pagesize=A4,
            leftMargin=2*cm, rightMargin=2*cm,
            topMargin=2*cm, bottomMargin=2*cm,
        )

        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle("AyoTitle", fontSize=24, textColor=PRIMARY,
                                  spaceAfter=6, fontName="Helvetica-Bold",
                                  alignment=TA_CENTER))
        styles.add(ParagraphStyle("AyoHeading", fontSize=14, textColor=PRIMARY,
                                  spaceBefore=12, spaceAfter=4,
                                  fontName="Helvetica-Bold"))
        styles.add(ParagraphStyle("AyoBody", fontSize=11, leading=18,
                                  textColor=DARK, spaceAfter=8))
        styles.add(ParagraphStyle("AyoMeta", fontSize=9, textColor=colors.grey,
                                  alignment=TA_CENTER))

        story = [
            Paragraph(topic.upper(), styles["AyoTitle"]),
            Paragraph(
                f"Generated by Ayo AI · {datetime.now().strftime('%B %d, %Y')}",
                styles["AyoMeta"]
            ),
            HRFlowable(width="100%", thickness=2, color=PRIMARY, spaceAfter=12),
            Spacer(1, 0.3*cm),
        ]

        # Parse content — detect headings (lines starting with # or in CAPS)
        for line in content.split("\n"):
            line = line.strip()
            if not line:
                story.append(Spacer(1, 0.2*cm))
            elif line.startswith("## "):
                story.append(Paragraph(line[3:], styles["AyoHeading"]))
                story.append(HRFlowable(width="50%", thickness=1,
                                        color=SECONDARY, spaceAfter=4))
            elif line.startswith("# "):
                story.append(Paragraph(line[2:], styles["AyoHeading"]))
            elif line.startswith("- ") or line.startswith("• "):
                story.append(Paragraph(f"• {line[2:]}", styles["AyoBody"]))
            else:
                story.append(Paragraph(line, styles["AyoBody"]))

        story.append(Spacer(1, 1*cm))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
        story.append(Paragraph("Created by Ayo AI — Your Personal AI Assistant",
                                styles["AyoMeta"]))

        doc.build(story)
        log.info(f"📄 PDF created: {path}")
        return path

    # ══════════════════════════════════════════════════════════════════════════
    # POWERPOINT
    # ══════════════════════════════════════════════════════════════════════════

    def create_ppt(self, topic: str, slides: list[dict], filename: str = None) -> str:
        """
        Create a PowerPoint presentation.
        slides: [{"title": str, "content": str|list[str]}, ...]
        Returns: saved file path
        """
        if not filename:
            safe = "".join(c if c.isalnum() else "_" for c in topic)[:30]
            filename = f"{safe}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        path = str(DOCS_DIR / filename)

        prs = Presentation()
        prs.slide_width  = Inches(13.33)
        prs.slide_height = Inches(7.5)

        PURPLE = RGBColor(0x7C, 0x3A, 0xED)
        CYAN   = RGBColor(0x06, 0xB6, 0xD4)
        WHITE  = RGBColor(0xFF, 0xFF, 0xFF)
        DARK   = RGBColor(0x0F, 0x17, 0x2A)

        # ── Title Slide ───────────────────────────────────────────────────────
        blank_layout = prs.slide_layouts[6]  # Blank
        title_slide  = prs.slides.add_slide(blank_layout)
        bg = title_slide.background.fill
        bg.solid()
        bg.fore_color.rgb = DARK

        # Purple accent bar
        accent = title_slide.shapes.add_shape(
            1, Inches(0), Inches(3.2), Inches(13.33), Inches(0.08)
        )
        accent.fill.solid()
        accent.fill.fore_color.rgb = PURPLE
        accent.line.fill.background()

        # Title text
        title_box = title_slide.shapes.add_textbox(
            Inches(1), Inches(2.5), Inches(11.33), Inches(1.5)
        )
        tf = title_box.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = topic.upper()
        p.font.size = Pt(40)
        p.font.bold = True
        p.font.color.rgb = WHITE
        p.alignment = PP_ALIGN.CENTER

        # Subtitle
        sub_box = title_slide.shapes.add_textbox(
            Inches(1), Inches(3.8), Inches(11.33), Inches(0.8)
        )
        stf = sub_box.text_frame
        sp = stf.paragraphs[0]
        sp.text = f"Generated by Ayo AI · {datetime.now().strftime('%B %Y')}"
        sp.font.size = Pt(18)
        sp.font.color.rgb = CYAN
        sp.alignment = PP_ALIGN.CENTER

        # ── Content Slides ────────────────────────────────────────────────────
        for slide_data in slides:
            slide = prs.slides.add_slide(blank_layout)
            bg = slide.background.fill
            bg.solid()
            bg.fore_color.rgb = RGBColor(0xF8, 0xFA, 0xFC)

            # Purple left sidebar
            bar = slide.shapes.add_shape(
                1, Inches(0), Inches(0), Inches(0.15), Inches(7.5)
            )
            bar.fill.solid()
            bar.fill.fore_color.rgb = PURPLE
            bar.line.fill.background()

            # Slide title
            t_box = slide.shapes.add_textbox(
                Inches(0.4), Inches(0.3), Inches(12), Inches(0.9)
            )
            ttf = t_box.text_frame
            tp = ttf.paragraphs[0]
            tp.text = slide_data.get("title", "")
            tp.font.size  = Pt(28)
            tp.font.bold  = True
            tp.font.color.rgb = DARK

            # Underline accent
            acc2 = slide.shapes.add_shape(
                1, Inches(0.4), Inches(1.1), Inches(3), Inches(0.06)
            )
            acc2.fill.solid()
            acc2.fill.fore_color.rgb = CYAN
            acc2.line.fill.background()

            # Content
            raw_content = slide_data.get("content", "")
            if isinstance(raw_content, list):
                content_lines = raw_content
            else:
                content_lines = [l.strip() for l in raw_content.split("\n") if l.strip()]

            c_box = slide.shapes.add_textbox(
                Inches(0.4), Inches(1.3), Inches(12.5), Inches(5.8)
            )
            ctf = c_box.text_frame
            ctf.word_wrap = True

            for i, line in enumerate(content_lines):
                para = ctf.paragraphs[0] if i == 0 else ctf.add_paragraph()
                if line.startswith("- ") or line.startswith("• "):
                    para.text = f"▸  {line[2:]}"
                    para.font.size = Pt(18)
                elif line.startswith("**") and line.endswith("**"):
                    para.text = line[2:-2]
                    para.font.bold = True
                    para.font.size = Pt(20)
                else:
                    para.text = line
                    para.font.size = Pt(18)
                para.font.color.rgb = DARK
                para.space_after = Pt(6)

        prs.save(path)
        log.info(f"📊 PowerPoint created: {path}")
        return path

    # ══════════════════════════════════════════════════════════════════════════
    # VIBE CODE
    # ══════════════════════════════════════════════════════════════════════════

    def vibe_code(self, description: str, code: str,
                  language: str = "html", filename: str = None) -> str:
        """
        Save generated code to a file and open it in the browser if HTML.
        Returns: saved file path
        """
        ext = {"html": "html", "python": "py", "javascript": "js",
               "css": "css", "markdown": "md"}.get(language.lower(), "txt")
        if not filename:
            safe = "".join(c if c.isalnum() else "_" for c in description)[:25]
            filename = f"vibe_{safe}_{datetime.now().strftime('%H%M%S')}.{ext}"

        path = str(DOCS_DIR / filename)
        Path(path).write_text(code, encoding="utf-8")

        # Auto-open HTML files in default browser
        if ext == "html":
            import subprocess
            subprocess.Popen(["start", path], shell=True)
            return f"Code generated and opened in browser: {path}"

        log.info(f"💻 Vibe code saved: {path}")
        return f"Code saved to: {path}"

    def open_document(self, path: str) -> str:
        """Open any document in the default app."""
        import subprocess
        subprocess.Popen(["start", path], shell=True)
        return f"Opening {Path(path).name}…"
